version: '3'

networks:
  backend:                       # Movies API, Redis, and MongoDB shared network
  frontend:                      # Mongo Express network
  profile-network:
    external: true
    name: 'mongo-network'        # 为Profile App提供的外部网络

volumes:
  profiledata:                   # MongoDB数据卷
  redisdata:                     # Redis数据卷

services:
  movies-api:
    container_name: movies-api
    image: doconnor/movies-api:1.0
    environment:
      - MONGODB_URI=mongodb://admin:secret@database:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    ports:
      - 9000:9000                # 映射Movies API端口9000到主机
    networks:
      - backend                  # 连接到backend网络
    depends_on:
      - database
      - redis

  database:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - backend                  # 连接到backend用于Movies API
      - frontend                 # 连接到frontend用于Mongo Express
      - profile-network          # 连接到profile-network用于Profile App
    volumes:
      - profiledata:/data/db

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - backend                  # 仅连接到backend网络
    volumes:
      - redisdata:/data

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081                # 将Mongo Express的8081端口映射到主机的8080端口
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=database
    networks:
      - frontend                 # 仅连接到frontend网络
    depends_on:
      - database
